In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import joblib

In [4]:
df = pd.read_csv('E:/Heart_Disease_Prediction/data/raw_merged_heart_dataset.csv')

In [5]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalachh,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [6]:
print(df.shape)

(2181, 14)

In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2181 entries, 0 to 2180
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       2181 non-null   int64
 1   sex       2181 non-null   int64
 2   cp        2181 non-null   int64
 3   trestbps  2181 non-null   object
 4   chol      2181 non-null   object
 5   fbs       2181 non-null   object
 6   restecg   2181 non-null   object
 7   thalachh  2181 non-null   object
 8   exang     2181 non-null   object
 9   oldpeak   2181 non-null   float64
 10  slope     2181 non-null   object
 11  ca        2181 non-null   object
 12  thal      2181 non-null   object
 13  target    2181 non-null   int64
dtypes: float64(1), int64(4), object(9)
memory usage: 238.7+ KB
None

In [8]:
print(df['target'].value_counts())

target
0    1099
1    1082
Name: count, dtype: int64

In [13]:
df = df.drop_duplicates()

In [14]:
df.shape

(894, 14)

In [20]:
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

In [21]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalachh,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2169,55,1,1,124,261,0,1,141,0,0.3,2,0,3,0
2173,50,1,0,128,204,1,1,156,1,1.0,1,0,0,0
2176,60,1,0,140,207,0,0,138,1,1.9,2,1,3,0
2179,54,1,1,154,232,0,0,164,0,0.0,2,1,2,0
2180,53,1,0,110,335,0,1,143,1,3.0,1,1,3,0